name: 'Continuous Benchmark'

description: 'Continuous Benchmark using GitHub pages as dash board'

inputs:
  name:
    description: 'Name of the benchmark. This value must be identical among all benchmarks'
    required: true
    default: 'Benchmark'
  tool:
    description: 'Tool to use get benchmark output. One of "cargo", ... (TODO)'
    required: true
  output-file-path:
    description: 'A path to file which contains the benchmark output'
    required: true
  gh-pages-branch:
    description: 'Branch for gh-pages'
    required: true
    default: 'gh-pages'
  benchmark-data-dir-path:
    description: 'Path to directory which contains JSON files benchmarks'
    required: true
    default: 'dev/bench'

runs:
  using: 'node12'
  main: 'index.js'
